Fixes #1600: Enable stream in server
loklak/loklak_server pull request #1601
Opened 2018-05-16 09:18 UTC by simsausaurabh

### Short description
I have:
- [X] There is a corresponding issue for this pull request.
- [X] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [X] There is only strictly only one commit per issue.

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

Fixes: #1600

2018-05-16 11:22 UTC, singhpratyush requested changes

2018-06-04 05:23 UTC, sudheesh001 requested changes
Are you running a MQTT server/broker for this to be enabled? We also then need to set up the infrastructure and then work on the streams accordingly. Mosquitto or MQTT are the ideal choices for streaming. This is a much needed feature. Thank you for taking time but it needs more work to make it work properly.

2018-06-04 08:00 UTC, simsausaurabh commented
No I am not running a MQTT server/broker. I am searching for already deployed MQTT servers. I also tried to deploy one but it didn't work, that's why keeping this on hold for a while. Once I get success in deploying or once I get already deployed free of cost MQTT server, I'll update the patch.

2018-08-22 14:22 UTC, simsausaurabh commented
Closing it as for now. Will send a patch once MQTT server/broker is deployed.

2018-08-22 14:22 UTC, closed without merging